#!/usr/bin/env bash

# need to install html-minifier first
# npm install html-minifier -g

if ! command -v html-minifier &>/dev/null; then
    echo "html-minifier could not be found, installing it"
    npm install html-minifier -g
fi

MINIFIER_OPTIONS="--collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --keep-closing-slash"
# MINIFIER_OPTIONS=""

#
# index.html
#

cat html/index.html |
    html-minifier ${MINIFIER_OPTIONS} |
    gzip |
    xxd -i -n IndexHtml |
    sed '1s/^/#include "htmldata.h" \n\n/' |
    sed 's/unsigned char /const unsigned char /' >index.cpp

#
# ap-config.html
#

cat html/ap-config.html |
    html-minifier ${MINIFIER_OPTIONS} |
    gzip |
    xxd -i -n ApConfigHtml |
    sed '1s/^/#include "htmldata.h" \n\n/' |
    sed 's/unsigned char /const unsigned char /' >ap-config.cpp

#
# sta-config.html
#

cat html/sta-config.html |
    html-minifier ${MINIFIER_OPTIONS} |
    gzip |
    xxd -i -n StaConfigHtml |
    sed '1s/^/#include "htmldata.h" \n\n/' |
    sed 's/unsigned char /const unsigned char /' >sta-config.cpp

#
# favicon.png
#

cat html/favicon.png |
    xxd -i -n FavIconPng |
    sed '1s/^/#include "htmldata.h" \n\n/' |
    sed 's/unsigned char /const unsigned char /' >favicon.cpp

#
# the header
#

echo "// HTML pages" >htmldata.h
echo "" >>htmldata.h

echo "extern const unsigned char IndexHtml[];" >>htmldata.h
echo "extern unsigned int IndexHtml_len;" >>htmldata.h
echo "" >>htmldata.h

echo "extern const unsigned char StaConfigHtml[];" >>htmldata.h
echo "extern unsigned int StaConfigHtml_len;" >>htmldata.h
echo "" >>htmldata.h

echo "extern const unsigned char ApConfigHtml[];" >>htmldata.h
echo "extern unsigned int ApConfigHtml_len;" >>htmldata.h
echo "" >>htmldata.h

echo "extern const unsigned char FavIconPng[];" >>htmldata.h
echo "extern unsigned int FavIconPng_len;" >>htmldata.h
